- files/etc/issue
- files/startup/simp_clean_reboot_fact.init
- files/startup/simp_clean_reboot_fact.service
SIMP-622 #comment migrated `files/` from `simp-common`
> (SIMP-622) Migrate `files/` from `simp-common`

- build/pupmod-simplib.spec
SIMP-626 #close #comment Obsoleted common and functions in .spec file
> (SIMP-626) Obsolete common and functions

- build/package_metadata.yaml
SIMP-627 #comment Restricted `simplib` to 4.2/5.1 in package_metadata
> (SIMP-627) Update package_metadata

- build/pupmod-simplib.spec
- manifests/sysconfig/init.pp
- spec/classes/sysconfig/init_spec.rb
- templates/etc/sysconfig/init.erb
Single user mode should be password protected.
SIMP-522 #close
> (SIMP-522) CCE-4241-6 Password protected single user mode.

- build/pupmod-simplib.spec
- lib/facter/simp_enabled.rb
Returns true if simp is included in the catalog.
SIMP-543 #close
Change-Id: I4e9df519e4b2c69e1d33f083a6c63456391048cc
> (SIMP-543) Added a simp_enabled fact.

- spec/classes/at_spec.rb
- spec/classes/chkrootkit_spec.rb
- spec/classes/cron_spec.rb
- spec/classes/etc_default/nss_spec.rb
- spec/classes/etc_default/useradd_spec.rb
- spec/classes/host_conf_spec.rb
- spec/classes/init_spec.rb
- spec/classes/issue_spec.rb
- spec/classes/ktune_spec.rb
- spec/classes/localusers_spec.rb
- spec/classes/login_defs_spec.rb
- spec/classes/modprobe_blacklist_spec.rb
- spec/classes/nsswitch_spec.rb
- spec/classes/prelink_spec.rb
- spec/classes/profile_settings_spec.rb
- spec/classes/resolv_spec.rb
- spec/classes/secure_mountpoints_spec.rb
- spec/classes/sudoers_spec.rb
- spec/classes/swappiness_spec.rb
- spec/classes/sysconfig/init_spec.rb
- spec/classes/timezone_spec.rb
- spec/classes/yum_schedule_spec.rb
SIMP-667 #comment updated rspec syntax in `simplib`
SIMP-769 #close #comment updated old rspec tests to `expects` syntax
> (SIMP-667) Updated rspec tests to `expects` syntax

- .fixtures.yml
- build/pupmod-simplib.spec
- manifests/chkrootkit.pp
- manifests/cron.pp
- manifests/host_conf.pp
- manifests/init.pp
- manifests/issue.pp
- manifests/libuser_conf.pp
- manifests/login_defs.pp
- manifests/modprobe_blacklist.pp
- manifests/nsswitch.pp
- manifests/prelink.pp
- manifests/profile_settings.pp
- manifests/secure_mountpoints.pp
- manifests/sysconfig/init.pp
- manifests/sysctl.pp
- manifests/yum_schedule.pp
- metadata.json
Enabling simplib module for compliance checking
SIMP-720 #comment
> (SIMP-720) Map 800-53 requirements to hiera

- .travis.yml
- CONTRIBUTORS
- README.md
- build/pupmod-simplib.spec
- lib/puppet/parser/functions/to_integer.rb
- lib/puppet/parser/functions/validate_between.rb
- manifests/sysconfig/init.pp
- metadata.json
- spec/classes/resolv_spec.rb
- spec/functions/to_integer_spec.rb
- spec/functions/to_string_spec.rb
* Added a to_integer() function
* Migrated to Semantic Versioning 2.0.0 for the RPM
SIMP-907 #comment Supporting function addition for migration to P4
> (SIMP-907) Add to_integer() function

- build/pupmod-simplib.spec
- manifests/params.pp
- metadata.json
- Migrated use_simp_pki to a global catalyst.
SIMP-894 #comment Fixes for issues discovered during testing
Change-Id: I3c55be0ee85740583dc0028b276a3821d778e7b6
> (SIMP-894) Fixed issues discovered during testing

- build/pupmod-simplib.spec
- lib/facter/gdm_version.rb
- metadata.json
Confined the fact on the existence of the gdm binary.
SIMP-1147 #close
> (SIMP-1147) Added the gdm_version fact from xwindows.

- build/rpm_metadata/requires
* Ported to new RPM build structure
* Validated compliance_markup dependencies
SIMP-1275 #comment validated compliance_markup mapping
> (SIMP-1275) Validate compliance_markup mapping

- CHANGELOG
- lib/facter/puppet_settings.rb
The puppet_settings fact had several issues.
This rewrite corrects these issues with much cleaner code.
SIMP-2038 #close
SIMP-2037 #close
> (SIMP-2038) Fix issues with puppet_settings

- CHANGELOG
- lib/facter/puppet_settings.rb
The puppet_settings fact had several issues.
This rewrite corrects these issues with much cleaner code.
SIMP-2039 #close
SIMP-2037 #close
> (SIMP-2039) Fix issues with puppet_settings

- Gemfile
- README.md
- Rakefile
- types/port/user.pp
- types/port/userport.pp
* Updated the README for the Data Types
* Removed the leftover userport.pp file
SIMP-1695 #comment Updated simplib documentation
> (SIMP-1695) Update documentation

- CHANGELOG
SIMP-2433 #comment Fix changelog order in simplib
> (SIMP-2443) Fix Changelog order

- .gitlab-ci.yml
> (SIMP-2423) Add .gitlab-ci.yml to pupmod-simp-simplib

- .gitlab-ci.yml
- CHANGELOG
- types/serverdistribution.pp
> (SIMP-2507) Add 'Simplib::Serverdistribution' type

- lib/puppet/parser/functions/passgen.rb
- metadata.json
- spec/spec_helper.rb
> (SIMP-2858) Move passgen to /var/simp

- .travis.yml
- CHANGELOG
- metadata.json
-updated the version from last release.
-updated travis.yml file with new versions
SIMP-2863 #close
SIMP-2748 #comment simplib updated
> (SIMP-2748) Update metadata.json file for simplib

- CHANGELOG
- lib/puppet/parser/functions/passgen.rb
> (SIMP-2878) Move simp_autofiles to Puppet vardir

- lib/puppet/parser/functions/passgen.rb
We still need to account for the fact that there will be multiple
disparate environments.
SIMP-2878 #close
> (SIMP-2878) Need to account for environments

- lib/facter/defaultgatewayiface.rb
Custom fact defaultgatewayiface not confined  to linux only systems
SIMP-2882 #close
> (SIMP-2882) Custom fact defaultgatewayiface not confined

- CHANGELOG
- types/packageensure.pp
> (SIMP-3177) Add package_ensure data type

- CHANGELOG
- lib/facter/fullrun.rb
Fix fullrun fact to not throw an error on non-POSIX
systems
SIMP-3309 #close
> (SIMP-3309) fullrun fact is not confined properly

- lib/puppet/functions/simplib/ip_to_cron.rb
- lib/puppet/functions/simplib/rand_cron.rb
Make function documentation match algorithm changes made
to previous commit.
> (SIMP-3280) Documentation fix for ip_to_cron and rand_cron

- metadata.json
Prep for tag and release
SIMP-3685 #comment pupmod-simp-simplib RPM prep
> (SIMP-3685) pupmod-simp-simplib - Fix metadata.json version

- CHANGELOG
- metadata.json
- spec/acceptance/suites/default/inspect_spec.rb
> (SIMP-3437) Bump to version 3.6.0

- CHANGELOG
- lib/puppet/parser/functions/validate_umask.rb
- metadata.json
> (SIMP-3915) Deprecate validate_umask

- CHANGELOG
- lib/puppet/functions/simplib/validate_re_array.rb
- lib/puppet/parser/functions/validate_re_array.rb
- metadata.json
- spec/functions/simplib/validate_re_array_spec.rb
> (SIMP-3912) Convert validate_re_array and write test

- CHANGELOG
- lib/puppet/functions/simplib/validate_sysctl_value.rb
- lib/puppet/parser/functions/validate_sysctl_value.rb
- spec/functions/simplib/validate_sysctl_value_spec.rb
> (SIMP-3914) Convert validate_sysctl_value and write test

- CHANGELOG
- lib/puppet/functions/simplib/nets2cidr.rb
- lib/puppet/parser/functions/nets2cidr.rb
- spec/functions/simplib/nets2cidr_spec.rb
> (SIMP-3937) Convert nets2cidr and write test

- CHANGELOG
- lib/puppet/functions/simplib/join_mount_opts.rb
- spec/functions/simplib/join_mount_opts_spec.rb
> (SIMP-3935) Convert join_mount_opts and write test

- CHANGELOG
Fix badly-merged changelog details
SIMP-3969 #comment simplib cleanup
> (SIMP-3969) simplib - cleanup CHANGELOG

- spec/acceptance/suites/default/passgen_spec.rb
> (SIMP-3999) Use appropriate hash algorithms in passgen acceptance test

- spec/functions/simplib/passgen_spec.rb
> (SIMP-3829) Skip spec test that fails on gitlab

- CHANGELOG
- lib/puppet/provider/reboot_notify/notify.rb
- metadata.json
- spec/unit/puppet/provider/reboot_notify/notify_spec.rb
- spec/unit/puppet/type/reboot_notify_spec.rb
> (SIMP-4798) Improved reboot_notify error handling

- CHANGELOG
- metadata.json
Version inadvertently bumped for last change
> (SIMP-MAINT) Fix version

- CHANGELOG
- lib/facter/ipa.rb
- spec/unit/facter/ipa_spec.rb
Changed Facter::Core::Execution.exec to Facter::Core::Execution.execute and added a timeout so the fact doesn't hang indefinitely.
> Added execute timeout

- CHANGELOG
- REFERENCE.md
- functions/in_bolt.pp
- metadata.json
- spec/functions/simplib/in_bolt_spec.rb
SIMP-6061 #comment provide a common mechanism for detecting if you are in a Bolt run.
> (SIMP-6061) Add a 'simplib::in_bolt' function

- CHANGELOG
- lib/puppet/functions/simplib/deprecation.rb
- lib/puppet/parser/functions/simplib_deprecation.rb
- spec/acceptance/suites/default/inspect_spec.rb
- spec/acceptance/suites/default/ipaddresses_spec.rb
- spec/acceptance/suites/default/nets2ddq_spec.rb
- spec/acceptance/suites/default/parse_hosts_spec.rb
- spec/acceptance/suites/default/strip_ports_spec.rb
- spec/acceptance/suites/default/to_integer_spec.rb
- spec/acceptance/suites/default/to_string_spec.rb
- spec/acceptance/suites/default/validate_array_member_spec.rb
- spec/acceptance/suites/default/validate_between_spec.rb
- spec/acceptance/suites/default/validate_bool_simp_spec.rb
- spec/acceptance/suites/default/validate_deep_hash_spec.rb
- spec/acceptance/suites/default/validate_net_list_spec.rb
- spec/acceptance/suites/default/validate_port_spec.rb
- spec/acceptance/suites/default/validate_uri_list_spec.rb
- spec/functions/simplib/deprecation_spec.rb
https://gitlab.com/simp/pupmod-simp-simplib/pipelines/55464984
> (SIMP-4071) Re-enable simplib deprecation warnings by default

- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/docker.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/ipa_fact/nodesets/default.yml
SIMP-6919 #comment pupmod-simp-simplib
> (SIMP-6919) Remove unnecessary EPEL repos in node sets

- CHANGELOG
- lib/puppet/type/reboot_notify.rb
- metadata.json
Fixes: [SIMP-5091](https://simp-project.atlassian.net/browse/SIMP-5091)
... for me; YMMV.
> (SIMP-5091) Fix uninitialized constant.

- CHANGELOG
- lib/puppet/functions/simplib/ip/family_hash.rb
- metadata.json
- spec/functions/simplib/ip/family_hash_spec.rb
simplib::ip::family_hash did not properly process 'unknown' entries
SIMP-7096 #comment fix simplib::ip::family_hash
> (SIMP-7096) Fix simplib::ip::family_hash

- lib/facter/simplib__sshd_config.rb
- lib/puppet/functions/simplib/caller.rb
- spec/acceptance/suites/caller_function/caller_spec.rb
- spec/acceptance/suites/caller_function/files/modules/testmod/manifests/init.pp
- spec/acceptance/suites/caller_function/files/modules/testmod/metadata.json
- spec/acceptance/suites/default/simplib__sshd_config_fact_spec.rb
- spec/unit/facter/simplib__sshd_config_spec.rb
* Add acceptance test for simplib__sshd_config
* Fix caller_function acceptance tests
> [SIMP-MAINT] Fix acceptance tests

- CHANGELOG
- functions/safe_filename.pp
- metadata.json
- spec/functions/safe_filename_spec.rb
- spec/unit/data_types/systemd/servicename_spec.rb
- types/systemd/servicename.pp
- simplib::safe_filename() => Replace unsafe characters with safe ones in
filename strings
- Simplib::Systemd::ServiceName => Data type for safe service name strings
SIMP-7822 #comment Additional helpers added
> [SIMP-7822] Added additional helpers

- CHANGELOG
- lib/facter/simplib__auditd.rb
- metadata.json
- spec/unit/facter/simplib__auditd_spec.rb
- Fixed the simplib__auditd fact so that it detects the state of the running
auditd process
SIMP-6740 #comment Fixed the simplib__auditd fact
> (SIMP-6740) simplib__auditd fact fix

- .rubocop.yml
- CHANGELOG
- Gemfile
- lib/facter/grub_version.rb
- lib/facter/init_systems.rb
- lib/facter/simp_puppet_settings.rb
- metadata.json
- spec/functions/simplib/validate_re_array_spec.rb
- spec/unit/facter/grub_version_spec.rb
- spec/unit/facter/init_systems_spec.rb
* grub_version was working but was doing pointless variable assignments
* Added a spec test
* init_systems would work on pretty much all modern systems by accident
but was not returning the collected array appropriately
* Added a spec test
* Other trivial fixups noticed while looking through the facts
SIMP-8346 #close
> (SIMP-8346) Fixed bugs grub_version & init_systems

- .gitlab-ci.yml
- Gemfile
- lib/facter/simplib__mountpoints.rb
- lib/facter/tmp_mounts.rb
- spec/acceptance/suites/windows/00_facter_spec.rb
- spec/acceptance/suites/windows/nodesets/default.yml
- spec/spec_helper_acceptance.rb
> (SIMP-8382) Confine tmp_mounts on directories

- CHANGELOG
- lib/facter/simplib_sysctl.rb
- metadata.json
Added to simplib_sysctl fact
SIMP-9133 #close
> (SIMP-9133) Add net.ipv6.conf.all.disable_ipv6

- functions/cron/to_systemd.pp
- spec/functions/cron/to_systemd_spec.rb
* Fixed
* Add support for multi-item entries
SIMP-9630 #comment fixed systemd cron conversion
> (SIMP-9630) Fix systemd cron conversion

- CHANGELOG
- lib/facter/simplib__networkmanager.rb
- metadata.json
- spec/unit/facter/simplib__networkmanager_spec.rb
* Also fixed the version number
SIMP-8955 #close
> (SIMP-8955) Fix simplib__networkmanager fact

- CHANGELOG
- lib/puppet/functions/simplib/gen_random_password.rb
- metadata.json
- spec/functions/simplib/gen_random_password_spec.rb
- Fixed
- Increased randomization in simplib::gen_random_password
SIMP-10456 #comment better password randomization for FIPS mode
> (SIMP-10456) Better password randomization

- .fixtures.yml
- CHANGELOG
- Gemfile
- lib/facter/ipa.rb
- metadata.json
- spec/acceptance/suites/ipa_fact/ipa_fact_spec.rb
- spec/unit/facter/ipa_spec.rb
> Fix ipa fact
