build/pupmod-simplib.spec

Ensure that the RPM has the appropriate Provides and Obsoletes clauses
for all of the other Puppet Module RPMs.
SIMP-532 #comment Update Provides and Obsoletes

(SIMP-532) Update Provides and Obsoletes

---

build/pupmod-simplib.spec
lib/facter/boot_dir_uuid.rb
lib/facter/defaultgateway.rb
lib/facter/defaultgatewayiface.rb
lib/facter/runlevel.rb
lib/facter/shmall.rb
metadata.json

Before this commit, the custom facts `boot_dir_uuid`, `defaultgateway`,
`defaultgatewayiface`, `runlevel`, `shmall` would report errors during
agent runs on Windows clients.
This patch confines the problem facts to the `:kernel` type `linux`.
SIMP-716 #close #comment Confined Linux facts that break Windows agents

(SIMP-716) Confine Linux facts that break Windows

---

lib/facter/ipv6_enabled.rb

If you completly disable ipv6 via options ipv6 disable=1 at module load
this fact throws annoying errors during every puppet run
adding -e will not print error and return ""
PS: Sorry for not creating an issue in your jira

Fix ipv6_enabled

---

build/pupmod-simplib.spec
lib/puppet/parser/functions/to_string.rb
spec/functions/to_string_spec.rb

To get the Puppet Linter to stop yelling about proper string casts on
single variables, I've added a to_string() function to make it quite
explicit.
SIMP-720 #comment Added to_string function for openldap::server::conf::threads
Change-Id: I21b1a322ca77444cc5c9946a14a6739f63f4fb07

(SIMP-720) Added a to_string() function

---

build/pupmod-simplib.spec
lib/puppet/parser/functions/localuser.rb
spec/acceptance/localusers_spec.rb

Function is now compatible with all versions of ruby and fixed
a return value bug.
SIMP-841 #close

(SIMP-841) Fixed bugs in the localusers function

---

build/pupmod-simplib.spec

Spec file referred to the wrong name for pupmod compliance.
SIMP-913 #close

(SIMP-913) Update spec to use proper compliance dependency

---

build/pupmod-simplib.spec
templates/etc/nsswitch.conf.erb

Modified nsswitch template to reference private _use_sssd and
_use_ldap logic, exclusively.
SIMP-920 #close

(SIMP-920) Nsswitch.conf configured ldap when sssd was enabled

---

.fixtures.yml
build/pupmod-simplib.spec
manifests/nsswitch.pp
metadata.json
spec/classes/nsswitch_spec.rb
spec/classes/swappiness_spec.rb

- _use_sssd now properly set
- updated spec tests to reflect sssd EL6.7+
- updated fixtures to use simp-master branch of augeasproviders_*
SIMP-939 #close
Change-Id: I701b53b75403aac479830bb0786cd5bc78272281

(SIMP-939) Fixed sssd/ldap logic in nsswitch.conf template

---

.fixtures.yml
.travis.yml
Gemfile
Rakefile
manifests/resolv.pp
manifests/secure_mountpoints.pp
metadata.json
spec/classes/init_spec.rb
spec/classes/resolv_spec.rb
spec/classes/secure_mountpoints_spec.rb
spec/spec_helper.rb

This commit contains prototype static assets for running spec tests when
`STRICT_VARIABLES=yes`
**NOTE:** The spec tests for this commit require v1.2.0i or above of
`simp-rspec-puppet-facts`
SIMP-1062 #close Updated static module assets in `pupmod-simp-simplib`
SIMP-1062 #comment Codifeid SELinux as `disabled` in secure mnts test
Change-Id: I41852569223c44bb3ad625c805d151deef121551

(SIMP-1062) Modeled new static module assets

---

CHANGELOG
manifests/sysctl.pp
metadata.json

Set sysctl `net.ipv4.tcp_challenge_ack_limit` to its maximum value to
mitigate CVE-2016-5696, off-path TCP hijack via a blind in-window attack
due to improperly rate-limited ACK segments.  Note that this does not
fix the vulnerability, it only makes it more difficult for an attacker
to exploit it.

(SIMP-1337) Mitigate CVE-2016-5696 via sysctl

---

manifests/swappiness.pp
spec/classes/swappiness_spec.rb

Before this commit, the `simplib::swappiness` class still used the
`sysctl::value` define instead of the `sysctl` type from
`augeasproviders_systctl`.  This resulted in a SyntaxError that broke
the catalog when the `absolute_swappiness` was used.
This commit fixes the issue by convering the class and its tests from
using `sysctl::value` to `sysctl`.
SIMP-1435 #close #comment Fix `swappiness` to use `sysctl` type
Change-Id: I93c7cf3bfffc925fccc6fb11cc7d1cabf04864b6

(SIMP-1435) Fix `swappiness` to use `sysctl` type

---

CHANGELOG
lib/puppet/functions/simplib/lookup.rb
metadata.json
spec/functions/simplib/lookup_spec.rb

This enhances the inbuilt lookup() function to check and see if the
passed value is defined in the global scope as a variable prior to
falling back to a normal lookup.
This means that any value that is set via an ENC or a standard class
declaration will be properly found.
SIMP-1694 #close

(SIMP-1694) Add the simplib::lookup function

---

lib/puppet/functions/simplib/lookup.rb
spec/functions/simplib/lookup_spec.rb

Per conversations with Henrik Lindberg, changed the scope to only lookup
global settings and actual parameters that have been assigned to
classes.
Note: This will only find assigned parameters that have *already* been
processed by the compiler, so order matters!

(SIMP-1694) Restrict lookup scope

---

spec/unit/data_types/dynamicport_spec.rb
spec/unit/data_types/emailaddress_spec.rb
spec/unit/data_types/port_spec.rb
spec/unit/data_types/randomport_spec.rb
spec/unit/data_types/systemport_spec.rb
spec/unit/data_types/umask_spec.pp
spec/unit/data_types/uri_spec.rb
spec/unit/data_types/userport_spec.rb

The previous location was not executed by default even though it was
copied from puppetlabs-stdlib.
SIMP-1695 #close Update spec test location for data types

(SIMP-1695) Ensure that the data type tests run

---

CHANGELOG
lib/puppet/parser/functions/passgen.rb
spec/functions/passgen_spec.rb

Only use characters in complexity mode 0 (a-zA-Z0-9.\) for
salts. While this hasn't seemed to have broken RHEL's shadow
handling, it has the potential to break other platforms
and libraries,  so clean it up anyway.
SIMP-2426 #close

(SIMP-2426) Clean up salt generation

---

CHANGELOG
functions/ldap/domain_to_dn.pp
metadata.json

This is to support the OpenLDAP rewrite as well as any other modules
that may need a reasonable base DN
SIMP-2180 #comment Added function for converting from domain to DN

(SIMP-2180) Added simplib::ldap::domain_to_dn

---

CHANGELOG
README.md
lib/facter/fips_ciphers.rb

The fips_ciphers fact returns the available OpenSSL FIPS ciphers on the
system. This will be used as the default ciphers set for OpenLDAP,
because it doesn't like the FIPS shortcut.
SIMP-2546 #comment added the fact
SIMP-2547 #close

(SIMP-2547) Add fips_ciphers fact

---

lib/puppet/functions/simplib/lookup.rb

Lookup would complain on systems that it could not find variables at
global scope. This disables the warning prior to the global lookup
being performed.
SIMP-2469 #comment Fix global lookup issue found during testing

(SIMP-2469) Ensure that lookup is safe

---

CHANGELOG
lib/puppet/parser/functions/simp_version.rb
metadata.json

The `simp_version` fact executes `rpm(8)` to find the version for SIMP.
Previously this was done with a hard-coded path, `/bin/rpm`, but this
broke on systems where the executable was installed elsewhere.  This
changes the call to set up PATH in the subshell before executing the
command.
SIMP-2937 #close

(SIMP-2937) Use PATH lookup for simp_version's rpm call

---

CHANGELOG
functions/inspect.pp
metadata.json
spec/functions/inspect_spec.rb

The original inspect() function is no longer user-friendly enough for
debugging.
This function has been added to actually print the value during the
Puppet run as a notify resource.
Care was taken to try to make it easy to note that this is for
debugging.
SIMP-2992 #comment Needed during debugging of array sets

(SIMP-2992) Added simplib::inspect debugger

---

CHANGELOG
functions/ldap/domain_to_dn.pp
metadata.json

* Use uppercase 'DC=' instead of lowercase 'dc=' so systems like active
directory can handle the output.
SIMP-2994 #close

(SIMP-2994) Use uppercase for LDAP DN strings in simplib::ldap::domain_to_dn

---

CHANGELOG
lib/facter/defaultgateway.rb
lib/facter/defaultgatewayiface.rb
metadata.json
spec/unit/facter/defaultgateway_spec.rb
spec/unit/facter/defaultgatewayiface_spec.rb

Implemented defaultgateway and defaultgatewayiface facts using
standard ip command to eliminate dependency on net-tools package.
SIMP-1486 #close

(SIMP-1486) Remove netstat from defaultgateway/defaultgatewayiface facts

---

CHANGELOG
lib/facter/simp_puppet_settings.rb
lib/facter/simplib_sysctl.rb
manifests/stages.pp
metadata.json

There have been several situations where various SIMP components really
needed to be wrapped in a Puppet stage to protect the rest of the
system from a particularly aggressive action (usually one that requires
a reboot).
This change adds a couple of SIMP stages that wrap the stdlib stages to
provide a buffer zone for SIMP-specific activities. This is not a
perfect solution but it will work better than just trying to tag onto
the existing stages that don't actually map to our use cases.
SIMP-3115 #comment Added buffer stages for module locking

(SIMP-3115) Added wrapper stages to simplib

---

CHANGELOG
lib/facter/boot_dir_uuid.rb
lib/facter/root_dir_uuid.rb

* Cleaned up the boot_dir_uuid fact
* Reverted the version number for the module since the last release was
3.2.0
SIMP-3138 #comment Added supporting root_dir_uuid fact for the fips module

(SIMP-3138) Added new root_dir_uuid fact

---

README.md
lib/puppet/functions/simplib/filtered.rb
lib/puppet/functions/simplib/mock_data.rb
spec/functions/simplib/filtered_spec.rb

Create a 'simplib::filtered' data_hash hiera v5 function that allows for passing through data_hash lookups, but only returns keys that match the filter list.
SIMP-3143 #close

(SIMP-3143) Create 'simplib::filtered' data_hash hiera v5 backend

---

CHANGELOG
functions/knockout.pp
spec/functions/knockout_spec.rb

- Due to lack of support for knockout_prefix for arrays in older versions
of Puppet, simp::knockout functionality has been moved to
simplib::knockout because multiple modules are using the function.
- A wrapper has been put around simp::knockout for backwards-compatibility
in our code.
SIMP-3302 #comment Moved functionality into simplib

(SIMP-3302) Move simp::knockout functionality into simplib

---

CHANGELOG
lib/facter/ipv6_enabled.rb
metadata.json

ipv6_enabled runs on all kernels, when the sysctl in question
is linux specific. This causes spurious errors on non-linux
systems
SIMP-3447 #close SIMP-1388 #close

(SIMP-3447) ipv6_enabled is not confined properly

---

CHANGELOG
Gemfile
lib/facter/fips_ciphers.rb
spec/unit/facter/fips_ciphers_spec.rb

- Returns nil if the openssl binary is not available
- Addresses https://github.com/simp/pupmod-simp-simp_grafana/issues/28
SIMP-3490 #close

(SIMP-3490) Updated the fips_ciphers fact

---

CHANGELOG
lib/puppet/functions/simplib/ip_to_cron.rb
lib/puppet/functions/simplib/rand_cron.rb
lib/puppet/parser/functions/ip_to_cron.rb
lib/puppet/parser/functions/rand_cron.rb
spec/functions/simplib/ip_to_cron_spec.rb
spec/functions/simplib/rand_cron_spec.rb

SIMP-3280 specifies to replace the IP-modulus-based algorithm in rand_cron (and thus ip_to_cron)
with a SHA256-based algorithm. This request was specifically meant to address a deficiency with
the randomness of client puppet agent runs scheduled by pupmod::agent::cron in certain
circumstances. (By default, pupmod::agent::cron uses rand_cron to determine the cron minute
for client's puppet agent run from the client's IP address.)
Since, empirical analysis of both the original and proposed algorithms for sets of servers in which both
the number of IP addresses is larger than the cron range and the IP addresses are assigned linearly,
the IP-modulus algorithm provides a better distribution across minutes in an hour, this PR instead
provides both algorithms and allows the user to select the …

(SIMP-3280) Add SHA256-based algorithm option to ip_to_cron/rand_cron

---

CHANGELOG
lib/puppet/parser/functions/validate_macaddress.rb
metadata.json
spec/type_aliases/simplib_macddress_spec.rb
types/macaddress.pp

* Create Simplib::Macaddress custom type
* Add deprecation notice to validate_macaddress() that references
Simplib::Macaddress as its replacement
* Write unit test
SIMP-3910 #close

(SIMP-3910) Create MAC address type and test

---

CHANGELOG
lib/facter/tmp_mounts.rb
metadata.json

The "findmnt" command does not exist on RHEL5 (and is not
available, afaict) and this causes an error:
undefined method `split' for nil:NilClass
in tmp_mounts.rb.  The fix I chose to implement just
skips the code block if "findmnt" returns no output.
SIMP-4015 #close

(SIMP-4015) Fix failure on tmp_mount fact on RHEL5

---

.gitlab-ci.yml
CHANGELOG
lib/puppet/functions/simplib/nets2ddq.rb
lib/puppet/functions/simplib/validate_array_member.rb
lib/puppet/functions/simplib/validate_between.rb
lib/puppet/functions/simplib/validate_bool.rb
lib/puppet/functions/simplib/validate_deep_hash.rb
lib/puppet/parser/functions/nets2ddq.rb
lib/puppet/parser/functions/simplib_deprecation.rb
lib/puppet/parser/functions/validate_array_member.rb
lib/puppet/parser/functions/validate_between.rb
lib/puppet/parser/functions/validate_bool_simp.rb
lib/puppet/parser/functions/validate_deep_hash.rb
metadata.json
spec/acceptance/suites/default/nets2ddq_spec.rb
spec/acceptance/suites/default/to_integer_spec.rb
spec/acceptance/suites/default/to_string_spec.rb
spec/acceptance/suites/default/validate_array_member_spec.rb
spec/acceptance/suites/default/validate_between_spec.rb
spec/acceptance/suites/default/validate_bool_simp_spec.rb
spec/acceptance/suites/default/validate_deep_hash_spec.rb
spec/functions/simplib/nets2cidr_spec.rb
spec/functions/simplib/nets2ddq_spec.rb
spec/functions/simplib/passgen_spec.rb
spec/functions/simplib/validate_array_member_spec.rb
spec/functions/simplib/validate_between_spec.rb
spec/functions/simplib/validate_bool.rb
spec/functions/simplib/validate_deep_hash_spec.rb

- Convert a subset of Puppet 3 functions to Puppet 4 and emit a
simplib deprecation warning when the Puppet 3 versions as called:
- simplib::nets2ddq() replaces deprecated nets2ddq().
- simplib::validate_array_member() replaces deprecated
validate_array_member().
- simplib::validate_between() replaces deprecated validate_between().
The new version fails validation, instead of returning false.
This behavior consistent with both how the method is used by SIMP
modules and the error behavior of all other simplib validate
functions.
- simplib::validate_bool() replaces deprecated validate_bool_simp().
- simplib::validate_deep_hash replaced validate_deep_hash.
- In simplib::validate_deep_hash, fixed validate_deep_hash bug in
which unknown keys in the Hash to check were not detected.
SIMP-3358 …

(SIMP-3358) Deprecate & convert Puppet 3 functions part 4

---

CHANGELOG
lib/puppet/functions/simplib/deprecation.rb
lib/puppet/functions/simplib/join_mount_opts.rb
lib/puppet/functions/simplib/validate_array_member.rb
lib/puppet/functions/simplib/validate_between.rb
lib/puppet/parser/functions/simplib_deprecation.rb
spec/acceptance/suites/default/inspect_spec.rb
spec/acceptance/suites/default/ipaddresses_spec.rb
spec/acceptance/suites/default/nets2ddq_spec.rb
spec/acceptance/suites/default/parse_hosts_spec.rb
spec/acceptance/suites/default/passgen_spec.rb
spec/acceptance/suites/default/strip_ports_spec.rb
spec/acceptance/suites/default/to_integer_spec.rb
spec/acceptance/suites/default/to_string_spec.rb
spec/acceptance/suites/default/validate_array_member_spec.rb
spec/acceptance/suites/default/validate_between_spec.rb
spec/acceptance/suites/default/validate_bool_simp_spec.rb
spec/acceptance/suites/default/validate_deep_hash_spec.rb
spec/acceptance/suites/default/validate_net_list_spec.rb
spec/acceptance/suites/default/validate_port_spec.rb
spec/acceptance/suites/default/validate_uri_list_spec.rb
spec/functions/simplib/deprecation_spec.rb

Disable simplib deprecation warnings, temporarily.
Will re-enable when we are ready to address the deprecations
in SIMP modules.
Removed trailing whitespace.
SIMP-4067 #close

(SIMP-4067) simplib: Disable simplib deprecation warnings by default

---

CHANGELOG
lib/facter/login_defs.rb
metadata.json
spec/unit/facter/login_defs_spec.rb

Returns a structured fact for the entire contents of /etc/login.defs
and defaults to returning 'uid_min' and 'gid_min' if they are not
present in the file
SIMP-3892 #comment add login_defs structured fact for use by other modules

(SIMP-3892) Add login_defs custom fact

---

.travis.yml
CHANGELOG
Gemfile
Rakefile
lib/facter/ipa.rb
metadata.json
spec/acceptance/suites/ipa_fact/ipa_fact_spec.rb
spec/acceptance/suites/ipa_fact/metadata.yml
spec/acceptance/suites/ipa_fact/nodesets/default.yml
spec/unit/facter/ipa_spec.rb

Created ipa fact that provides the IPA domain and server to which
a host is connected, when the host is joined to the IPA domain
AND is able to communicate with the IPA server.
As written, this fact cannot to distinguish between the following cases:
* No connectivity to the IPA server when joined to an IPA domain.
* The host is no longer joined to an IPA domain.
Addressing this deficiency is not trivial and will need to be done
in a follow-on ticket.
NOTE: At first blush, it seems like the fact could have been written
to pull information locally from the IPA configuration file,
/etc/ipa/default.conf.  However, the information in this file is not
definitive. Specifically, if the client has been removed from the IPA
domain using the IPA server GUI instead of running the IPA client …

(SIMP-4214) simplib: Create ipa fact

---

CHANGELOG
functions/ldap/domain_to_dn.pp
spec/functions/ldap/domain_to_dn_spec.rb

* Added an option to simplib::ldap::domain_to_dn to allow users to
choose whether or not they want to upcase the LDAP attribute strings.
This allows users to work around bugs in various client applications
as necessary
SIMP-4266 #comment Fixed issue discovered in setting up Dogtag

(SIMP-4266) Update domain_to_dn function

---

Gemfile
lib/facter/ipa.rb
spec/acceptance/suites/ipa_fact/ipa_fact_spec.rb
spec/acceptance/suites/ipa_fact/nodesets/default.yml
spec/unit/facter/ipa_spec.rb

The IPA server doesn't support FIPS mode on EL6, so that test should be
skipped in that scenario.
SIMP-4264 #comment work done
SIMP-4272 #close
SIMP-4327 #close Fix ipa fact

(SIMP-4264) simplib: Refine ipa fact

---

README.md
functions/assert_metadata.pp
functions/inspect.pp
functions/ldap/domain_to_dn.pp
lib/puppet/functions/simplib/deprecation.rb
lib/puppet/functions/simplib/gen_random_password.rb
lib/puppet/functions/simplib/ipaddresses.rb
lib/puppet/functions/simplib/join_mount_opts.rb
lib/puppet/functions/simplib/lookup.rb
lib/puppet/functions/simplib/nets2cidr.rb
lib/puppet/functions/simplib/nets2ddq.rb
lib/puppet/functions/simplib/parse_hosts.rb
lib/puppet/functions/simplib/passgen.rb
lib/puppet/functions/simplib/strip_ports.rb
lib/puppet/functions/simplib/to_integer.rb
lib/puppet/functions/simplib/to_string.rb
lib/puppet/functions/simplib/validate_array_member.rb
lib/puppet/functions/simplib/validate_between.rb
lib/puppet/functions/simplib/validate_bool.rb
lib/puppet/functions/simplib/validate_deep_hash.rb
lib/puppet/functions/simplib/validate_net_list.rb
lib/puppet/functions/simplib/validate_port.rb
lib/puppet/functions/simplib/validate_re_array.rb
lib/puppet/functions/simplib/validate_sysctl_value.rb
lib/puppet/functions/simplib/validate_uri_list.rb
lib/puppetx/simp/simplib.rb
spec/functions/simplib_spec.rb
types/port/dynamic.pp

- Seperated Puppet 3 and Puppet later functions.
- Marked Puppet 3 functions as derecated.
- Added info about stages, extentions, and custom types.
- Added examples for funstions that had them.
SIMP-4262 #close
SIMP-4369 close
SIMP-4370 close
SIMP-4371 close

(SIMP-4262) Update the simplib README file.

---

CHANGELOG
lib/puppet/provider/reboot_notify/notify.rb
lib/puppet/type/reboot_notify.rb
manifests/reboot_notify.pp
spec/acceptance/suites/default/reboot_notify_spec.rb
spec/classes/reboot_notify_spec.rb
spec/spec_helper.rb
spec/unit/puppet/provider/reboot_notify/notify_spec.rb
spec/unit/puppet/type/reboot_notify_spec.rb
types/puppetloglevel.pp

* Adds two parameters :disable_alerting and :control_only to the
'reboot_notify' custom type.
* :disable_alerting => Disable alerts for all reboot_notify resources
* :control_only     => Indicate that this entry should not be added to
the generated file
* Added a 'reboot_control_metadata' section to the on-system record file
* Added a `simplib::reboot_notify` class to allow for ease of global
metadata manipulation.
* We may want to move this into its own module at some point
* Fixed file paths that were not Windows compatible
* Improved some tests
SIMP-4816 #close

(SIMP-2519) Add ability to silence reboot notify

---

CHANGELOG
lib/puppet/type/init_ulimit.rb
spec/unit/puppet/type/init_ulimit_spec.rb

* This updates init_ulimit to allow it to work properly with `puppet
generate types`
* A typo was also fixed in the composite namevar
SIMP-4863 #close

(SIMP-4826) Update init_ulimit for generate types

---

.gitlab-ci.yml
.puppet-lint.rc
.travis.yml
CHANGELOG
functions/hash_to_opts.pp
spec/functions/hash_to_opts_spec.rb

- Add `simplib::hash_to_opts` which turns a hash into a string with each
key prefixed with '--' and connected to each value with '='. Useful
for generating commands
SIMP-4885 #close

(SIMP-4885) Add hash_to_opts function

---

CHANGELOG
manifests/install.pp
spec/defines/install_spec.rb

This moves and refactors the `gnome::install` defined type into simplib
since it was getting used in multiple modules.
SIMP-4936 #comment extracted 'gnome::install' into 'simplib::install'

(SIMP-4936) Add 'simplib::install' defined type

---

CHANGELOG
lib/facter/cmdline.rb
spec/unit/facter/cmdline_spec.rb

Currently only the last value is captured where the key appears multiple times. This commit fixes this into an array.

(SIMP-4956) Fix parsing of multiple values for parameters

---

CHANGELOG
README.md
REFERENCE.md
lib/puppet/functions/simplib/assert_optional_dependency.rb
lib/puppet/functions/simplib/module_exist.rb
metadata.json
spec/functions/simplib/assert_optional_dependency_spec.rb
spec/functions/simplib/deprecation_spec.rb
spec/functions/simplib/module_exist_spec.rb

Added a function `assert_optional_dependency` that allows users to fail
if expected functionality is not present in the current environment's
module set. This provides the ability for users to support multiple
vendor modules without forking.
SIMP-4447 #close

(SIMP-4447) Add 'assert_optional_dependency' func

---

CHANGELOG
lib/facter/simp_puppet_settings.rb
metadata.json
spec/acceptance/suites/default/validate_simp_puppet_settings_spec.rb

Before this patch, the `puppet_settings` fact incorrectly interpolated
variables using the `[main]` section's settings instead of `[master]`.
A significant consequence of this has been that the fact supplies
incorrect paths for `[master]` settings, notably `server_datadir`:
```sh
[root@puppet ~]# puppet config print --section master server_datadir
/opt/puppetlabs/server/data/puppetserver/server_data
[root@puppet ~]# facter -p puppet_settings.master.server_datadir
/opt/puppetlabs/puppet/cache/server_data
```
As a consequence, `pupmod::master::sysconfig` ends up using the puppet
agent's vardir instead of puppetserver's (SIMP-5021), causing the
puppetserver service to fail when upgrading to new versions of
puppet-agent (SIMP-5383)―particularly when upgrading from SIMP 6.1 to
SIMP 6.2.
This …

(SIMP-5383) Fix bug in `puppet_settings` fact

---

CHANGELOG
lib/facter/simplib_sysctl.rb
lib/facter/uid_min.rb
metadata.json

Hi folk, this PR takes care of the following two errors that show up on non-Linux OS's:
Under Windows:
```
puppet : [1;31mError: Facter: error while resolving custom fact "simplib_sysctl": undefined method `strip' for nil:NilClass[0m
+ CategoryInfo          : NotSpecified: ([1;31mError: F...il:NilClass[0m:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
```
This was due to it not having sysctl at all.
Under Mac OS X (and Windows if I recall correctly):
```
error while resolving custom fact "uid_min": undefined method `empty?' for nil:NilClass
```
This was due to some slightly confused unless login (at least per my and my coworkers read).  We simplified the section a bit.
Let me know if you have any concerns or questions about the patch!

Fix errors on non-Linux OS's

---

.gitlab-ci.yml

OEL servers are included in the default.yml for the ipa_fact suite
SIMP-5722 #close

(SIMP-5722) gitlab job specifies nonexistent node set

---

CHANGELOG
lib/puppet/functions/simplib/validate_sysctl_value.rb
metadata.json
spec/functions/simplib/validate_sysctl_value_spec.rb

simp::sysctl added support for setting fs.inotify.max_user_watches
inline with many vendor recommendations.
The simplib::validate_sysctl_value function was updated to ensure that
users do not try to set fs.inotify.max_user_watches to a value that
exceeds system RAM.
SIMP-5855 #comment validate fs.inotify.max_user_watches

(SIMP-5855) Validate fs.inotify.max_user_watches

---

.travis.yml
CHANGELOG
README.md
functions/assert_metadata.pp
functions/hash_to_opts.pp
metadata.json
spec/type_aliases/shadowpass_spec.rb
types/libcrypt/bcrypt.pp
types/libcrypt/bigcrypt.pp
types/libcrypt/bsdi_extended_des.pp
types/libcrypt/des.pp
types/libcrypt/md5_freebsd.pp
types/libcrypt/md5_sun.pp
types/libcrypt/nthash.pp
types/libcrypt/scrypt.pp
types/libcrypt/sha1.pp
types/libcrypt/sha2_256.pp
types/libcrypt/sha2_512.pp
types/libcrypt/yescript.pp
types/shadowpass.pp

This change adds the Simplib::ShadowPass data type which checks against
all valid entries for /etc/shadow for the password field.
SIMP-5919 #comment Create Simplib::ShadowPass type to use

(SIMP-5919) Add Simplib::ShadowPass

---

.fixtures.yml
.gitlab-ci.yml
CHANGELOG
Gemfile
REFERENCE.md
lib/puppet/functions/simplib/dlookup.rb
lib/puppet/functions/simplib/gen_random_password.rb
lib/puppet/functions/simplib/nets2cidr.rb
lib/puppet/functions/simplib/nets2ddq.rb
lib/puppet/functions/simplib/parse_hosts.rb
lib/puppet/functions/simplib/strip_ports.rb
lib/puppet/functions/simplib/to_integer.rb
lib/puppet/functions/simplib/validate_array_member.rb
lib/puppet/functions/simplib/validate_between.rb
lib/puppet/functions/simplib/validate_bool.rb
lib/puppet/functions/simplib/validate_deep_hash.rb
lib/puppet/functions/simplib/validate_net_list.rb
lib/puppet/functions/simplib/validate_port.rb
lib/puppet/functions/simplib/validate_re_array.rb
lib/puppet/functions/simplib/validate_sysctl_value.rb
lib/puppet/functions/simplib/validate_uri_list.rb
spec/fixtures/hieradata/default.yaml
spec/fixtures/hieradata/simplib_dlookup_overrides.yaml
spec/functions/simplib/dlookup_spec.rb
spec/spec_helper.rb

- Add a 'defined type' lookup capability, `simplib::dlookup` that provides a
consistent method for retrieving defined type parameters from Hiera in an
opt-in manner.
- Fixed various YARD documentation issues
SIMP-5940 #comment Add function to support defined type global lookups

(SIMP-5940) Add simplib::dlookup function

---

CHANGELOG
lib/puppet/functions/simplib/ipaddresses.rb
metadata.json

Add missing ':' in the function declaration.

(SIMP-MAINT) Fix syntax on simplib::ipaddresses signature

---

CHANGELOG
metadata.json
spec/type_aliases/cron/weekday_entry_spec.rb
types/cron/weekday_entry.pp

Fixed bug in Simplib::Cron::Weekday type alias in which a numeric
value of 0 was not allowed.
SIMP-6304 #close

(SIMP-6304) Simplib::Cron::Weekday does not allow numeric 0

---

CHANGELOG
lib/puppet/parser/functions/array_union.rb
lib/puppet/parser/functions/generate_reboot_msg.rb
lib/puppet/parser/functions/get_ports.rb
lib/puppet/parser/functions/h2n.rb
lib/puppet/parser/functions/ip_is_me.rb
lib/puppet/parser/functions/localuser.rb
lib/puppet/parser/functions/mapval.rb
lib/puppet/parser/functions/validate_array_of_hashes.rb
lib/puppet/parser/functions/validate_float.rb
metadata.json

Deprecated Puppet 3 functions that are not used by any SIMP
modules.  The functions will be removed in a future release,
unless SIMP receives requests from users to convert them to
namespaced Puppet 4.x functions.
- array_union
- generate_reboot_msg
- get_ports
- h2n
- ip_is_me
- localuser
- mapval
- validate_array_of_hashes
- validate_float
SIMP-6319 #close

(SIMP-6319) Deprecate unused simplib functions

---

CHANGELOG
lib/puppet/parser/functions/array_include.rb
lib/puppet/parser/functions/array_size.rb

Deprecated simplib Puppet 3 functions for which corresponding,
though not identically behaving, Puppet builtins or stdlib
functions exist.  The functions will be removed in a future
release, unless SIMP receives requests from users to convert
them to namespaced Puppet 4.x functions.
- array_include() can often be replaced with stdlib member()
- array_size() can often be replaced with the Puppet builtin length()
SIMP-6320 #close

(SIMP-6320) Deprecate duplicate Puppet 3 functions

---

CHANGELOG
REFERENCE.md
lib/puppet/functions/simplib/simp_version.rb
lib/puppet/parser/functions/simp_version.rb
metadata.json
spec/functions/simplib/simp_version_spec.rb

- Converted simp_version Puppet 3 function to a Puppet 4
version, simplib::simp_version
- Added a unit test for simplib::simp_version
- Added deprecation warning to simp_version
SIMP-6251 #close

(SIMP-6251) Convert simp_version to Puppet 4 function

---

CHANGELOG
lib/puppet/parser/functions/slice_array.rb

Deprecated simplib's Puppet 3 slice_array for which a
corresponding, though not identically behaving, Puppet
builtin slice() exists.
NOTE: simplib's slice_array() is only used by pupmod-simp-iptables
and has functionality very specific to that module (i.e., split_char
logic to generate port ranges in iptables rules).  So, in lieu of
creating simplib::slice_array() from slice_array(), we are going
to create iptables::slice_array from slice_array() in
pupmod-simp-iptables.
SIMP-6252 #comment pupmod-simp-simplib

(SIMP-6252) Deprecate Puppet 3 slice_array

---

CHANGELOG
lib/puppet/functions/simplib/simp_version.rb
lib/puppet/parser/functions/simp_version.rb
metadata.json
spec/functions/simplib/simp_version_spec.rb

- updated simp_version function to use Puppet::Util::Execution.execute
instead of backtics.  This avoids a GLIBC error triggered by JRuby 9K.
SIMP-6506 #comment Also needs simp module update.

(SIMP-6506) Out Of Memory Error

---

CHANGELOG
lib/facter/fips_enabled.rb
metadata.json
spec/acceptance/suites/default/fips_enabled_fact_spec.rb
spec/acceptance/suites/default/inspect_spec.rb
spec/acceptance/suites/default/ipaddresses_spec.rb
spec/acceptance/suites/default/nets2ddq_spec.rb
spec/acceptance/suites/default/parse_hosts_spec.rb
spec/acceptance/suites/default/passgen_spec.rb
spec/acceptance/suites/default/strip_ports_spec.rb
spec/acceptance/suites/default/to_integer_spec.rb
spec/acceptance/suites/default/to_string_spec.rb
spec/acceptance/suites/default/validate_array_member_spec.rb
spec/acceptance/suites/default/validate_between_spec.rb
spec/acceptance/suites/default/validate_bool_simp_spec.rb
spec/acceptance/suites/default/validate_deep_hash_spec.rb
spec/acceptance/suites/default/validate_net_list_spec.rb
spec/acceptance/suites/default/validate_port_spec.rb
spec/acceptance/suites/default/validate_uri_list_spec.rb
spec/acceptance/suites/prelink_fact/prelink_fact_spec.rb

Some version of facter have a built-in 'fips_enabled' fact. We now defer
to that one prior to adding our own fact.
Note: I was unable to determine how to properly unit test this but,
since the entire change is just checking for one item in Facter prior to
creating the fact, this isn't vastly different from the previous code
version (which also didn't have a unit test)
SIMP-6591 #close

(SIMP-6515) Defer to inbuilt fips_enable fact

---

.fixtures.yml
.gitlab-ci.yml
.travis.yml
CHANGELOG
metadata.json

- Removed Puppet 4 support, as Puppet has removed the Puppet 4 RPMs from
their yum repos.  This means all the Puppet 4 acceptance tests fail.
- Pinned the version of stdlib to 5.2.0 in the .fixtures.yml, as the
version on master is beyond the upper bound allowed in this
component's metadata.json.

(SIMP-MAINT) Prep for release - remove Puppet 4

---

CHANGELOG
lib/puppet/functions/simplib/deprecation.rb
lib/puppet/parser/functions/simplib_deprecation.rb
metadata.json
spec/functions/simplib/deprecation_spec.rb

- added check for environment variable,
SIMPLIB_NOLOG_DEPRECATIONS, to disable SIMP function
deprecation warnings.  (This has no impact on
puppet deprecation warnings)

(SIMP-6745) SIMP Deprecation warnings

---

CHANGELOG
lib/puppet/functions/simplib/passgen.rb

- Update the passgen function so it uses the process user id to check
permissions on files instead of the puppet user.  This will allow
stand alone processes to complete without error and still keep
the checks for the puppet server working.

(SIMP-5356) Passgen in stand alone

---

CHANGELOG
REFERENCE.md
lib/puppet/functions/simplib/ip/family_hash.rb
spec/functions/simplib/ip/family_hash_spec.rb

Add `simplib::ip::family_hash` function that takes an IP address or
Array of IP addresses and returns a Hash with the addresses broken down
by family with additional helpful metadata
SIMP-7096 #comment Add simplib::ip::family_hash

(SIMP-7096) Add simplib::ip::family_hash function

---

CHANGELOG
lib/facter/simplib__firewalls.rb

The fact was returning an empty array on Windows systems

(SIMP-MAINT) Confine the simplib__firewalls fact

---

CHANGELOG
lib/facter/simplib__sshd_config.rb
metadata.json
spec/unit/facter/simplib__sshd_config_spec.rb

- Fix an issue in the simplib__sshd_config fact that would cause the daemon to
start on an EL6 system that did not already have it running
SIMP-7572 #close

(SIMP-7572) Fix simplib__sshd_config fact

---

.gitlab-ci.yml
.travis.yml
Gemfile

This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7917 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-simplib
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-simplib
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855

(SIMP-7848) Add PE2019.8 to pupmod-simp-simplib GL pipeline

---

CHANGELOG
REFERENCE.md
metadata.json
spec/unit/data_types/hostname_spec.rb
types/systemd/servicename.pp

- Fixed Simplib::Systemd::ServiceName to accept instance services
- Added 'any' and 'ALL' to the data_types/hostname spec test
SIMP-7822 #comment Fix Simplib::Systemd::ServiceName data type

(SIMP-7822) Fix Simplib::Systemd::ServiceName

---

CHANGELOG
lib/puppet/functions/simplib/debug/inspect.rb
metadata.json
spec/functions/simplib/debug/inspect_spec.rb

Fixed:
* Bolt does not set scope.source. The code was reworked to optionally
pull scope.source and simply insert the scope as a string as a
fallback.
SIMP-8590 #close

(SIMP-8590)  Fix simplib::debug::inspect with Bolt

---

CHANGELOG
Gemfile
metadata.json
types/puppet/metadata/os_support.pp

Fixed:
- Allow the operatingsystemrelease to be optionally defined in
metadata.json operatingsystem_support

(SIMP-MAINT) Fix OS support data type

---

.github/workflows/pr_glci.yml
.github/workflows/pr_glci_manual.yml
.github/workflows/pr_tests.yml
.gitlab-ci.yml

This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9333] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-simplib
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-simplib
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …

(SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-simplib

---

spec/acceptance/suites/windows/nodesets/default.yml

This patch replaces a deprecated Vagrant windows-server box with
devopsgroup-io/windows_server-2012r2-standard-amd64-nocm
[SIMP-9521] #close
[SIMP-9521]: https://simp-project.atlassian.net/browse/SIMP-9521

(SIMP-9521) Replace troubled Windows Vagrant box

---

.rubocop.yml
CHANGELOG
Gemfile.project
REFERENCE.md
lib/puppet/functions/simplib/params2hash.rb
metadata.json
spec/functions/simplib/params2hash_spec.rb
spec/spec_helper.rb
spec/spec_helper_acceptance.rb

Added:
- Add a `simplib::params2hash()` function to return all of the calling scope's
parameters as a Hash
SIMP-9427 #comment added simplib::params2hash() to make sssd management easier

(SIMP-9427) Add simplib::params2hash()

---

.fixtures.yml
.gitlab-ci.yml
CHANGELOG
lib/facter/ipa.rb
spec/acceptance/nodesets/default.yml
spec/acceptance/suites/ipa_fact/ipa_fact_spec.rb
spec/acceptance/suites/ipa_fact/nodesets/default.yml
spec/acceptance/suites/ipa_fact/nodesets/oel.yml
spec/spec_helper_acceptance.rb
spec/unit/facter/ipa_spec.rb

* Fixes
* Fix the IPA fact
* Changes (@lnemsick-simp)
* Add a Puppet 7 acceptance test
* Fixe ipa_fact test suite
* Reinstate GitLab test jobs for caller_function, ipa_fact, and prelink_fact
suites
* Split default nodeset for ipa_fact suite into nodesets for CentOS and Oracle
boxes and then added corresponding *el8 nodes to them
* Fail acceptance tests if no examples are executed.
SIMP-9666 #comment pupmod-simp-simplib acceptance tests configured
SIMP-10175 #close
SIMP-10303 #close

(SIMP-10175) simplib Add Puppet 7 acceptance test

---

spec/acceptance/suites/default/inspect_spec.rb

Fixed log normalization for the simplib::inspect acceptance
test that was failing with the latest Puppet 7
SIMP-10433 #close

(SIMP-10433) simplib::inspect acceptance test fail Puppet7

---

CHANGELOG
Gemfile
lib/facter/ipa.rb
metadata.json
spec/unit/facter/ipa_spec.rb

Change klist to klist -s to so that it returns 1 when credentials cache cannot be read or is expired, thereby triggering the following kinit.
el7, el8, simp/sssd, simp/simp_ipa
Without this the ipa fact fails and the simp/sssd module removes the ipa domain and provider files if the credential cache is expired.

klist -> klist -s

---

.github/workflows/release_rpms.yml
.github/workflows/tag_deploy.yml
Gemfile

This commit rolls up various improvements to the GHA tag & release
workflows, particularly:
* Tagged releases build a matrix of RPMs: (EL8 *and* EL7)
* Tagged release logic supports pre/post-release tag formats
* New arguments in `release_rpms.yml`: `path_to_build` and `verbose`
* Ensure jobs run on `ubuntu-latest`
* Fixes for variable edge cases and inter-job dependencies
The patch enforces a standardized asset baseline using simp/puppetsync,
and may apply other updates to ensure conformity.
[SIMP-10697] #close
[SIMP-10633] #comment Add `release_rpms` to pupmod-simp-simplib
[SIMP-10697]: https://simp-project.atlassian.net/browse/SIMP-10697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10633]: …

(SIMP-10633) Update standardized assets

---

CHANGELOG
lib/puppet/functions/simplib/passgen/legacy/passgen.rb
metadata.json

#205 broke `puppet lookup --compile`, which is essential to troubleshoot Hiera lookups when using the top-scope manifest variables in the stock `manifests/site.pp`.  The defaults introduced in that patch assume that the Puppet user is the user executing the command/process.  If the user is root using the default umask of a SIMP server, this result in files that the Puppet Server's `puppet` user will not be able to read.
This patch uses the Puppet settings to look up the configured Puppet user instead of the owner of the current process.
Fixes #267, same root problem as [SIMP-7228]
[SIMP-7228]: https://simp-project.atlassian.net/browse/SIMP-7228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow root to run `puppet lookup --compile`

---

CHANGELOG
Gemfile
functions/module_metadata/os_supported.pp
lib/puppet/functions/simplib/assert_optional_dependency.rb
metadata.json
spec/acceptance/suites/windows/nodesets/default.yml
spec/functions/assert_metadata_spec.rb
spec/functions/module_metadata/assert_spec.rb
spec/functions/simplib/assert_optional_dependency_spec.rb
spec/functions/simplib/simp_version_spec.rb
spec/spec_helper_acceptance.rb
spec/unit/facter/defaultgateway_spec.rb
spec/unit/facter/defaultgatewayiface_spec.rb
spec/unit/facter/fips_ciphers_spec.rb
spec/unit/facter/init_systems_spec.rb
spec/unit/facter/ipa_spec.rb
spec/unit/facter/login_defs_spec.rb
spec/unit/facter/prelink_spec.rb
spec/unit/facter/puppet_settings_spec.rb
spec/unit/facter/simplib__auditd_spec.rb
spec/unit/facter/simplib__crypto_policy_state_spec.rb
spec/unit/facter/simplib__mountpoints_spec.rb
spec/unit/facter/simplib__networkmanager_spec.rb
spec/unit/facter/simplib__sshd_config_spec.rb

- Fixed
- Allow `assert_optional_dependency` to handle extended version strings
(Alpha, Beta, RC, 1.2.3.4, etc...)
- Allow `module_metadata::os_supported` to handle metadata where the
version is not specified (all versions supported)
- Changed
- Support all versions of known OSs
Needs simp/rubygem-simp-rspec-puppet-facts#43
Closes #271

Better `assert_optional_dependency`

---

CHANGELOG
lib/puppet/functions/simplib/passgen/legacy/passgen.rb
metadata.json

The latest passgen broke spec and acceptance tests for EE; `Puppet.settings[:user]` defaults to `puppet` even on systems where there is no puppet user.  This patch checks for the existence of the intended passgen (Puppet) user, and if it doesn't exist it defaults to the owner of the process running passgen.

Relax passgen UID/GID logic

---

.github/workflows/pr_tests.yml
.gitignore
.gitlab-ci.yml
.puppet-lint.rc
Gemfile
REFERENCE.md
functions/cron/to_systemd.pp
functions/ldap/domain_to_dn.pp
functions/module_metadata/assert.pp
spec/functions/ldap/domain_to_dn_spec.rb

This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.

Finalize RockyLinux 8 support

---

CHANGELOG
lib/facter/simplib__crypto_policy_state.rb
metadata.json
spec/unit/facter/simplib__crypto_policy_state_spec.rb

RHEL 8 has two locations in which crypto-policies are stored. 
- /etc/crypto-policies/policies/*.pol For user generated custom crypto policies
- /usr/share/crypto-policies/policies/*.pol For built in systems crypto policies
Presently the simplib__crypto_policy_state fact is only checking system crypto policy directory.
See RHEL documentation. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening#creating-and-setting-a-custom-system-wide-cryptographic-policy_using-the-system-wide-cryptographic-policies

(SIMP-10745) Fix simplib__crypto_policy_state fact
